-- app_data
CREATE USER app_data IDENTIFIED BY "2zeCj8wVC3AKXIf"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_code
CREATE USER app_code IDENTIFIED BY "v6bEo9wDde3tyl1"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_admin
CREATE USER app_admin IDENTIFIED BY "hFZpoDTool63TB3"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_user
CREATE USER app_user IDENTIFIED BY "3TJgUsY7hYimw0m"
ENABLE EDITIONS;
